# Generated by Django 6.0.5 on 2026-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='idx_prt_token',
            old_name='idx_password_reset_tokens_token',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='idx_prt_user',
            old_name='idx_password_reset_tokens_user_id',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='idx_prt_status',
            old_name='idx_password_reset_tokens_status',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='idx_prt_expires',
            old_name='idx_password_reset_tokens_expires',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
